server:
  port: 18080  # 配置端口
spring:
  datasource:
#    url: jdbc:mysql://192.168.214.128:3306/drug?useUnicode=true&characterEncoding=utf8
    url: jdbc:mysql://yeah.gold:3306/drug?useUnicode=true&characterEncoding=utf8
    username: root
    password: 123456
  mvc:
    format:
      date-time: yyyy-MM-dd HH:mm:ss # 日期对象Date 与字符串转换的格式，针对于表单提交的数据
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss # 日期对象Date 与字符串的转换格式 针对于json数据格式
mybatis:
  mapper-locations: classpath:/mappers/*.xml # 配置xml文件所在路径为路径下的mapper包
logging:
  level:
    edu.nchu.bootdemo.dao: debug

